version: '2'
services:
  db:
    image: postgres
  bundle:
    image: busybox
    volumes:
      - /bundle
  web:
    tty: true
    stdin_open: true
    build: ./api
    image: worddiary_web
    command: ./init-rails.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes_from:
      - bundle
  client:
    build: ./client
    image: worddiary_client
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - ./client:/client
      - /client/node_modules

volumes:
  node_modules:
