version: '2'
services:
  db:
    image: postgres
  bundle:
    image: worddiary_web
    volumes:
      - /bundle
  web:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/word_diary
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
    volumes_from:
      - container:web-sync:rw
      - bundle
  webpacker:
    image: worddiary_web
    command: bundle exec bin/webpack-dev-server
    ports:
      - "8080:8080"
    volumes:
      - .:/word_diary

volumes:
  web-sync:
    external: true
