version: '2'
services:
  db:
    image: postgres
  bundle:
    image: busybox
    volumes:
      - /bundle
  web:
    tty: true
    stdin_open: true
    build: .
    image: worddiary_web
    command: ./init-rails.sh
    volumes:
      - .:/word_diary
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes_from:
      - container:web-sync:rw
      - bundle
  webpacker:
    image: worddiary_web
    command: ./wait-for-it.sh web:3000 -t 180 -- ./init-webpacker.sh
    ports:
      - "8080:8080"
    volumes:
      - .:/word_diary
    depends_on:
      - web
volumes:
  web-sync:
    external: true
